let playerInt,progreso=JSON.parse(localStorage.getItem("progreso")||"[]");
window.addEventListener("DOMContentLoaded",()=>{tabs();buscarInit();cats();conf();inst();appsRender();libRender();});
function tabs(){const t=document.querySelectorAll(".bottom-nav button"),s=document.querySelectorAll("section");t.forEach(b=>b.onclick=()=>{t.forEach(x=>x.classList.remove("active"));s.forEach(a=>a.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active");});}
function buscarInit(){searchBtn.onclick=()=>{const q=searchInput.value.trim();if(q)buscar(q);};}
async function buscar(q){const u=`https://api.themoviedb.org/3/search/movie?api_key=${TMDB_API_KEY}&query=${encodeURIComponent(q)}&language=es-ES`;const r=await fetch(u);const d=await r.json();render(d.results);}
function cats(){document.querySelectorAll(".cat").forEach(c=>c.onclick=()=>gen(c.dataset.genre));}
async function gen(id){const u=`https://api.themoviedb.org/3/discover/movie?api_key=${TMDB_API_KEY}&with_genres=${id}&language=es-ES`;const r=await fetch(u);const d=await r.json();render(d.results);}
function render(l){const c=document.getElementById("resultados");c.innerHTML="";if(!l.length){c.innerHTML="<p>No hay resultados</p>";return;}l.forEach(m=>{const i=m.poster_path?`https://image.tmdb.org/t/p/w500${m.poster_path}`:"";const d=document.createElement("div");d.className="card";d.innerHTML=`<img src="${i}"><h3>${m.title}</h3>`;d.onclick=()=>det(m);c.appendChild(d);});}
function det(m){detalleFondo.style.backgroundImage=`url(https://image.tmdb.org/t/p/w500${m.backdrop_path})`;detalleTitulo.textContent=m.title;detalleDescripcion.textContent=m.overview||"Sin descripción.";document.getElementById("detalle").classList.remove("hidden");document.getElementById("buscar").classList.add("hidden");currentMovie=m;}
verAhora.onclick=()=>play();
const player=playerModal.querySelector("video"),time=playerTime;closePlayer.onclick=closeP;
function play(){playerModal.classList.remove("hidden");player.src="https://www.w3schools.com/html/mov_bbb.mp4";player.play();clearInterval(playerInt);playerInt=setInterval(tiempo,500);}
function closeP(){playerModal.classList.add("hidden");player.pause();clearInterval(playerInt);if(currentMovie){const idx=progreso.findIndex(x=>x.id===currentMovie.id);if(idx>=0)progreso[idx].time=player.currentTime;else progreso.push({id:currentMovie.id,title:currentMovie.title,time:player.currentTime});localStorage.setItem("progreso",JSON.stringify(progreso));libRender();}time.textContent="00:00 / 00:00";}
function tiempo(){const c=player.currentTime||0,d=player.duration||0;time.textContent=`${fmt(c)} / ${d?fmt(d):"00:00"}`;}
function fmt(s){const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),se=Math.floor(s%60);return[h,m,se].map(v=>v<10?"0"+v:v).join(":");}
function conf(){darkMode.onchange=e=>{document.body.style.background=e.target.checked?"#000":"linear-gradient(180deg,#0f1b2e,#0a58ca)";};logout.onclick=()=>{localStorage.clear();location.href="login.html";};}
function inst(){let p;const b=document.getElementById("installBtn");window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();p=e;b.style.display="block";});b.onclick=async()=>{if(!p)return alert("Ya instalada ✅");p.prompt();await p.userChoice;p=null;};}
function appsRender(){const a=document.getElementById("appsList"),l=[{n:"Netflix",d:"Series y películas",s:"⭐⭐⭐⭐⭐"},{n:"Spotify",d:"Música y podcasts",s:"⭐⭐⭐⭐"},{n:"YouTube",d:"Videos online",s:"⭐⭐⭐⭐⭐"}];a.innerHTML="";l.forEach(x=>{const c=document.createElement("div");c.className="card";c.innerHTML=`<div class='info'><h3>${x.n}</h3><p>${x.d}</p><p>${x.s}</p><button>Instalar</button></div>`;a.appendChild(c);});}
function libRender(){const c=document.getElementById("libraryList");c.innerHTML="";if(!progreso.length){c.innerHTML="<p>No hay películas guardadas.</p>";return;}progreso.forEach(x=>{const d=document.createElement("div");d.className="card";d.innerHTML=`<h3>${x.title}</h3><p>Progreso: ${Math.floor(x.time)}s</p><button onclick='ver(${x.id})'>Reanudar</button>`;c.appendChild(d);});}
function ver(id){const f=progreso.find(x=>x.id===id);if(f){playerModal.classList.remove("hidden");player.src="https://www.w3schools.com/html/mov_bbb.mp4";player.currentTime=f.time;player.play();clearInterval(playerInt);playerInt=setInterval(tiempo,500);}}
